/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => JobsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribe': typeof SubscribeRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribe': typeof SubscribeRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/subscribe': typeof SubscribeRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/jobs/new': typeof JobsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/subscribe'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/subscribe'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/login'
    | '/subscribe'
    | '/customers/$customerId'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/jobs/$jobId'
    | '/jobs/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  InvoicesRoute: typeof InvoicesRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubscribeRoute: typeof SubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsNewRoute: typeof JobsNewRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
  JobsNewRoute: JobsNewRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  InvoicesRoute: InvoicesRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  SubscribeRoute: SubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
